name: ${name}
main: ${main}
version: ${version}
author: ${author}
api-version: 1.19.4

depend:
  - packetevents

softdepend:
  - PlaceholderAPI
  - TAB
  - SkinsRestorer

libraries:
  - com.github.ben-manes.caffeine:caffeine:3.2.0

commands:
  nametags:
    description: Reload and debug commands
    permission: nametags.command.admin
