[versions]
shadow = "8.3.6"
runPaper = "2.3.1"

paper = "1.21.5-R0.1-SNAPSHOT"

placeholderapi = "2.11.6"
packetevents = "2.8.0"
entitylib = "+1f4aeef-SNAPSHOT"
tab = "5.2.0"
skinsrestorer = "15.6.4"
bstats = "3.1.0"

junit-jupiter = "5.13.0"

[libraries]
paper = { module = "io.papermc.paper:paper-api", version.ref = "paper" }

placeholderapi = { module = "me.clip:placeholderapi", version.ref = "placeholderapi" }
packetevents = { module = "com.github.retrooper:packetevents-spigot", version.ref = "packetevents" }
entitylib = { module = "me.tofaa.entitylib:spigot", version.ref = "entitylib" }
tab = { module = "com.github.NEZNAMY:TAB-API", version.ref = "tab" }
skinsrestorer = { module = "net.skinsrestorer:skinsrestorer-api", version.ref = "skinsrestorer" }
bstats = { group = "org.bstats", name = "bstats-bukkit", version.ref = "bstats" }

junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit-jupiter" }

[plugins]
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
run-paper = { id = "xyz.jpenilla.run-paper", version.ref = "runPaper" }
